In [54]:
from tensorflow.keras.models import load_model
import pickle 
import pandas as pd 
import numpy as np

In [55]:
## load the trained model,sacler pickle,onehot encoder 
model=load_model('model.h5')

## load the encoders and saclers 
with open('label_encoder_gender.pkl','rb') as f: 
    label_encoder_gender=pickle.load(f)

with open('onehot_encoder_geo.pkl','rb') as f: 
    label_encoder_geo=pickle.load(f)

with open('scaler.pkl','rb') as f: 
    scaler=pickle.load(f)

In [56]:
## Example input data

input_data={
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age':40,
    'Tenure':3,
    'Balance': 60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [57]:
input_df=pd.DataFrame([input_data])
input_df.head()

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [58]:
## ONe hot encode the categorical features

geo_encoded=label_encoder_geo.transform([[input_data['Geography']]])
geo_encoded_df=pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df.head()

/Users/anupdangi/Desktop/AnupAI/Research/DS_ML_DL_NLP_BOOTCAMP/venv/lib/python3.9/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [59]:
input_df=pd.DataFrame([input_data])
input_df.head()

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [60]:
## Encode categoriacal variables 
input_df['Gender']=label_encoder_gender.transform([[input_data['Gender']]])

/Users/anupdangi/Desktop/AnupAI/Research/DS_ML_DL_NLP_BOOTCAMP/venv/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [61]:
input_data

{'CreditScore': 600,
 'Geography': 'France',
 'Gender': 'Male',
 'Age': 40,
 'Tenure': 3,
 'Balance': 60000,
 'NumOfProducts': 2,
 'HasCrCard': 1,
 'IsActiveMember': 1,
 'EstimatedSalary': 50000}

In [62]:
input_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1            50000

[1 rows x 10 columns]

In [63]:
## concatenate the one hot encoded geo features with the original dataframe and drop the original 'Geography' column 

input_df=pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df],axis=1)
input_df.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [64]:
input_scaled = scaler.transform(input_df)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- EstimatedSalary
Feature names seen at fit time, yet now missing:
- Exited

In [47]:
## Predict Churn 
prediction=model.predict(input_scaled)

1/1 [==============================] - 0s 17ms/step

In [48]:
prediction_proba=prediction[0][0]

In [36]:
if prediction_proba>0.5:
    print(f"The customer is likely to churn with a probability of {prediction_proba:.2f}")
else:
    print(f"The customer is not likely to churn with a probability of {prediction_proba:.2f}")

The customer is not likely to churn with a probability of 0.06